#!/usr/bin/env python
import subprocess
import optparse
import random
import glob
import time

parser = optparse.OptionParser()
parser.add_option("-p", "--path", type="string", dest = "path", help = "path to get images from")
parser.add_option("-d", "--delay", type="int", dest = "delay", default = 600, help = "delay between image switches")
parser.add_option("-e", "--extensions", type="string", dest = "extensions", default = "png,jpg,jpeg,gif", help = "comma separated list of allowed extensions")
parser.add_option("-c", "--command", type="string", dest = "command", default = "nitrogen --set-zoom-fill %f", help = "command to execute on wallpaper change, replaces %f with the path to the wallpaper")

history = set()

options, args = parser.parse_args()
extensions = options.extensions.lower().split(",")

def getFileList():
	fl = glob.glob(options.path + "*.*")
	fl = filter(lambda f: f.rsplit(".", 1)[1].lower() in extensions, fl)
	return set(fl)

while True:
	time.sleep(options.delay)
	fl = getFileList()
	available = fl - history
	selected = random.choice(list(available))
	history.add(selected)
	if len(history) >= len(fl):
		history.clear()
		history.add(selected)
	pr = subprocess.Popen(options.command.replace("%f", selected), shell = True)
	pr.wait()
