#!/usr/bin/env python
import subprocess
import optparse
import random
import glob
import time

parser = optparse.OptionParser()
parser.add_option("-p", "--path", type="string", dest = "path", help = "path to get images from")
parser.add_option("-d", "--delay", type="int", dest = "delay", default = 600, help = "delay between image switches")
parser.add_option("-e", "--extensions", type="string", dest = "extensions", default = "png,jpg,jpeg,gif", help = "comma separated list of allowed extensions")
parser.add_option("-c", "--command", type="string", dest = "command", default = "nitrogen --set-zoom-fill %f", help = "command to execute on wallpaper change, replaces %f with the path to the wallpaper")
parser.add_option("-i", "--instant", action="store_true", dest = "instant", default = False, help = "don't wait before first wallpaper change")

history = set()

options, args = parser.parse_args()
options.extensions = options.extensions.lower().split(",")
if not options.path.endswith("/"):
	options.path += "/"

def getFileList(path):
	fl = glob.glob(path + "*.*")
	fl = filter(lambda f: f.rsplit(".", 1)[1].lower() in options.extensions, fl)
	return set(fl)

def changeWallpaper(image):
	pr = subprocess.Popen(options.command.replace("%f", selected), shell = True)
	pr.wait()

firstLoop = True

while True:
	if options.instant and firstLoop:
		firstLoop = False
	else:
		time.sleep(options.delay)
	fl = getFileList(options.path)
	available = fl - history
	selected = random.choice(list(available))
	history.add(selected)
	if len(history) >= len(fl):
		history.clear()
		history.add(selected)
	changeWallpaper(selected)
